name: CodeNarc Scan

on:
  push:
    paths:
      - '**.groovy'
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download CodeNarc
        run: |
          curl -L -o CodeNarc.jar https://repo1.maven.org/maven2/org/codenarc/CodeNarc/3.6.0/CodeNarc-3.6.0-all.jar

      - name: Run CodeNarc
        run: |
          java -jar CodeNarc.jar \
            -basedir=src \
            -rulesetfiles=rulesets/basic.xml,rulesets/braces.xml,rulesets/naming.xml,rulesets/unnecessary.xml,rulesets/security.xml,rulesets/braces.xml,\rulesets/concurrency.xml,\rulesets/convention.xml,\rulesets/design.xml,\rulesets/dry.xml,\rulesets/enhanced.xml,\rulesets/exceptions.xml,\rulesets/formatting.xml,\rulesets/generic.xml,\rulesets/grails.xml,\rulesets/groovyism.xml,\rulesets/imports.xml,\rulesets/jdbc.xml,\rulesets/junit.xml,\rulesets/logging.xml,\rulesets/naming.xml,\rulesets/security.xml,\rulesets/serialization.xml,\rulesets/size.xml,\rulesets/unnecessary.xml,\rulesets/unused.xml \
            -report=console \
            -report=html:build/reports/codenarc-report.html


