name: CodeNarc Scan

on:
  push:
    paths:
      - '**.groovy'
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # <-- REQUIRED NOW

      - name: Download CodeNarc
        run: |
          curl -L -o CodeNarc-3.3.0-all.jar https://github.com/CodeNarc/CodeNarc/releases/download/v3.3.0/CodeNarc-3.3.0-all.jar

      - name: Run CodeNarc
        run: |
          java -jar CodeNarc-3.3.0-all.jar \
            -basedir=src \
            -rulesetfiles=rulesets/basic.xml \
            -report=console
